### ISSUE TITLE
Deploy Live Demo of App to Heroku

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elm-datepicker#3]
`As a` **developer** considering using this elm package in my project,
`I want` to try a "Live Demo" of the `datepicker`
`So that` I can decide if it meets my needs.

We _could_ (_should_) deploy this to `ellie` https://ellie-app.com a "standalone" demo.
But if we deploy it to Heroku we can display several "variations" thus showing that it's "configurable". #2 

@Danwhy https://dashboard.heroku.com/apps/elm-datepicker is "reserved".
Please share your Heroku Email address in Gitter once you are ready to deploy this. 😉 

# Todo
+ [x] publish demo/example to heroku: https://elm-datepicker.herokuapp.com/
  + [x] ensure that new versions are _automatically_ published when PRs are merged 
  see: https://github.com/dwyl/learn-heroku#3-use-heroku-web-ui-to-deploy-the-application
+ [x]  Make demo link _prominent_ in the repo (_towards the top_) so people can click through the examples _early_ while they are evaluating the package.
+ [x]  ensure that one of the examples is visible by ***`default`*** when visiting the example page, a blank page is not v. user-friendly (_even if it is "obvious" after a few seconds that you need to click on one of the examples to view it, it still requires that initial thought. `#DontMakeMeThink`_)
+ [x] Request _feedback_ on the demo/example website. We should _always_ be inviting feedback.
+ [x] link _directly_ to https://elm-datepicker.herokuapp.com/#Styled in readme.
![image](https://user-images.githubusercontent.com/194400/45051747-d9203500-b07c-11e8-9408-a245c8f81363.png)

**Comment by karinakozarova** [comment]
This issue looks like it should be closed. Is there more work to be done?

**Comment by nelsonic** [comment]
Hi @karinakozarova _thank you_ for reminding us of this issue.
As noted in my comment in: https://github.com/dwyl/elm-datepicker/pull/23#pullrequestreview-119921499
I feel that we _can_ do more on this. (_deploying the example is a **good start** but you have to go scrolling for the link to the demo and when you click on the link it shows a blank page with some links ..._): https://elm-datepicker.herokuapp.com/
![image](https://user-images.githubusercontent.com/194400/40011493-e41f8252-579f-11e8-88d1-e578944612a9.png)

As a Result I have added a Todo List with checklist items to the description above.

For example, the Demo app has been deployed to Heroku (in May):
![image](https://user-images.githubusercontent.com/194400/45023741-1fe73e00-b02f-11e8-845f-760f8612cc7c.png)

But there is no deployment _pipeline_: https://dashboard.heroku.com/apps/elm-datepicker/deploy/heroku-git
![image](https://user-images.githubusercontent.com/194400/45023574-af402180-b02e-11e8-9ec8-a81a2356ee0f.png)
Which means that the _latest_ updates/bug-fixes (August) are not reflected on the demo site ...
![image](https://user-images.githubusercontent.com/194400/45023797-460cde00-b02f-11e8-8c12-92e8106730cc.png)

deployment should be _automatic_. 

Four clicks later and it's setup to deploy _automatically_ from the `master` branch:
![image](https://user-images.githubusercontent.com/194400/45023671-ed3d4580-b02e-11e8-911a-fffab7e9bbf3.png)

I _acknowledge_ that my initial instructions were incomplete. 
Therefore I am rectifying them and doing the work.
Because I cannot expect someone to "guess" what the acceptance criteria is
or do work they were not expecting to do ...

**Comment by nelsonic** [comment]
@iteles PR awaiting review: https://github.com/dwyl/elm-datepicker/pull/35 Please/Thanks! 👍

**Comment by nelsonic** [comment]
latest version _automatically_ deployed: https://dashboard.heroku.com/apps/elm-datepicker/activity
![image](https://user-images.githubusercontent.com/194400/45057023-69b24180-b08c-11e8-87da-e60c340f30a2.png)

**Comment by nelsonic** [comment]
Styled example shown by default: https://elm-datepicker.herokuapp.com/
![image](https://user-images.githubusercontent.com/194400/45057091-a120ee00-b08c-11e8-9b53-9a04442294a5.png)

**Comment by stevensonmt** [comment]
Slightly off-topic, but can you post the steps you took for deploying to heroku? Not clear how that works with elm.
